In [1]:
import numpy as np

### Creating a Layer 

In [9]:
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
weights = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

bias = np.array([0, 0, 0, 1])

c = np.dot(inputs, weights.T) + bias

In [10]:
c

array([[0, 0, 0, 1],
       [0, 1, 0, 2],
       [0, 0, 1, 2],
       [0, 1, 1, 3]])

### Coding 2 layers

In [11]:
import numpy as np

inputs = [[1, 2, 3, 2.5],
          [2., 5., -1., 2],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

# Convert lists to numpy arrays
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)

# Calculate the output of the first layer
layer1_outputs = np.dot(inputs_array, weights_array.T) + biases_array

# Calculate the output of the second layer
layer2_outputs = np.dot(layer1_outputs, weights2_array.T) + biases2_array

print(layer2_outputs)


[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
