### Dense Layer Class

In [3]:
import nnfs
from nnfs.datasets import spiral_data
import numpy as np
nnfs.init()


In [5]:
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.01*np.random.randn(n_inputs,n_neurons) # rows = n_inputs, columns = n_neurons
        self.biases = np.zeros((1,n_neurons))  # 1 row, n_neurons columns
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights)+self.biases 
    
x,y = spiral_data(samples=100,classes=3)

dense1 = Layer_Dense(2,3)

dense1.forward(x)

print(dense1.output[0:10])
        

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.61496298e-05 -5.70940247e-05 -1.16960771e-04]
 [-7.69893813e-05 -4.75328154e-04 -2.12466970e-04]
 [-1.19454686e-04 -6.26299181e-04 -3.77396704e-04]
 [-1.59333722e-04 -8.86327529e-04 -4.81519091e-04]
 [-1.44521880e-04 -1.16747292e-03 -2.80698237e-04]
 [-2.32432416e-04 -1.09792443e-03 -7.86150631e-04]
 [-2.78763153e-04 -1.55423908e-03 -8.40916007e-04]
 [-3.01691325e-04 -1.92443607e-03 -8.06041353e-04]
 [-2.80801381e-04 -2.14678515e-03 -5.97577542e-04]]
