### Broadcasting and Sum rule in Python

In [12]:
import numpy as np
A = [[1, 2, 3], [4, 5, 6], [7, 8,9]]
print(np.sum(A))


print(np.sum(A, axis = 0))
print(np.sum(A, axis = 0).shape)


print(np.sum(A, axis = 0,keepdims=True))
print(np.sum(A, axis = 0,keepdims=True).shape)


print(np.sum(A, axis = 1))
print(np.sum(A, axis = 1).shape)


print(np.sum(A, axis = 1,keepdims=True))
print(np.sum(A, axis = 0,keepdims=True).shape)

print(np.max(A))
print(np.max(A,axis=0,keepdims=True))

45
[12 15 18]
(3,)
[[12 15 18]]
(1, 3)
[ 6 15 24]
(3,)
[[ 6]
 [15]
 [24]]
(1, 3)
9
[[7 8 9]]
